echo updates
git-svn-id: file:///svn/rdup/trunk@715 0f4cb41f-7f08-0410-98f9-8ec83d93c06f

diff --git a/sh-tools/hist.sh.in b/sh-tools/hist.sh.in
--- a/sh-tools/hist.sh.in
+++ b/sh-tools/hist.sh.in
@@ -52,7 +52,7 @@ while getopts ":b:hdVzk" o; do
                 k) keyfile=$OPTARG;;
                 h) usage && exit;;
                 V) version && exit;;
-                \?) echo "** $PROGNAME: Invalid option" > /dev/fd/2; usage && exit;;
+                \?) echo "** $PROGNAME: Invalid option" >&2; usage && exit;;
         esac
 done
 if [ -z $backupdir ]; then
diff --git a/sh-tools/yesterday.sh.in b/sh-tools/yesterday.sh.in
--- a/sh-tools/yesterday.sh.in
+++ b/sh-tools/yesterday.sh.in
@@ -100,7 +100,7 @@ while getopts ":n:b:k:cCNdhzV" o; do
                 C) Ccopy=1;;
                 h) usage && exit;;
                 V) version && exit;;
-                \?) echo "** $0: Invalid option" >/dev/fd/2; usage && exit;;
+                \?) echo "** $0: Invalid option" >&2; usage && exit;;
         esac
 done
 if [[ -z $backupdir ]]; then
@@ -110,7 +110,7 @@ shift $((OPTIND - 1))
 
 if [[ ! -z $keyfile ]]; then
         if [[ ! -r $1 ]]; then
-                echo "** $0: Cannot read keyfile \`$1': failed" > /dev/fd/2
+                echo "** $0: Cannot read keyfile \`$1': failed" >&2
                 exit 1
         fi
 fi
