documentation updates and made restore behave better with the new names"
git-svn-id: file:///svn/rdup/trunk@910 0f4cb41f-7f08-0410-98f9-8ec83d93c06f

diff --git a/sh-wrapper/rdup-snapshot.in b/sh-wrapper/rdup-snapshot.in
--- a/sh-wrapper/rdup-snapshot.in
+++ b/sh-wrapper/rdup-snapshot.in
@@ -7,6 +7,7 @@
 prefix=@prefix@
 exec_prefix=@exec_prefix@
 datadir=@datadir@/rdup
+sysconfdir=@sysconfdir@/rdup
 
 # shared stuff
 source $datadir/shared.sh
@@ -20,7 +21,7 @@ usage() {
         echo
         echo OPTIONS:
         echo " -b DIR     backup directory"
-        echo " -c REMOTE  dump the backup on a remote machine with ssh"
+        echo " -c REMOTE  dump the backup on a remote machine with ssh (not impl)"
         echo " -k KEYFILE encrypt all files, using crypt.pl"
         echo " -z         compress all files, using gzip.pl"
         echo " -a         write extended attributes with uid/gid"
@@ -46,7 +47,10 @@ what() {
 
 PROGNAME=$0
 NOW=`date +%Y%m/%d`
-BACKUPDIR=/tmp/backup
+OPT=""
+R_OPT=""
+ETC="@sysconfdir@/rdup"
+
 while getopts ":ab:k:l:c:N:vzxehV" o; do
         case $o in
                 b) BACKUPDIR="$OPTARG"
@@ -55,6 +59,9 @@ while getopts ":ab:k:l:c:N:vzxehV" o; do
                         exit 1
                 fi
                 ;;
+                a) OPT="$OPT -a";;
+                v) OPT="$OPT -v";;
+                x) R_OPT="$R_OPT -x";;
                 h) usage && exit;;
                 V) version && exit;;
         esac
@@ -65,7 +72,6 @@ if [[ $# -eq 0 ]]; then
         exit 1
 fi
 
-ETC="/etc/rdup"
 STAMP="$ETC/$HOSTNAME.$(basename $1).timestamp"
 LIST="$ETC/$HOSTNAME.$(basename $1).list"
 
@@ -76,17 +82,19 @@ if [[ ! $? ]]; then
         exit 1
 fi
 
-what; purpose=$? # save return code from what2do
+what; purpose=$? # save return code from what
 case $purpose in
         0)
         _echo2 "INCREMENTAL DUMP"
-        @sbindir@/rdup -N $STAMP $LIST $@ | @sbindir@/rdup-snap -b $BACKUPDIR/$NOW
+        @sbindir@/rdup $R_OPT -N $STAMP $LIST $@ | \ 
+        @sbindir@/rdup-snap $OPT -b $BACKUPDIR/$NOW
         ;;
         1)
         _echo2 "FULL DUMP"
         rm -f $LIST
         rm -f $STAMP
-        @sbindir@/rdup -N $STAMP $LIST $@ | @sbindir@/rdup-snap -b $BACKUPDIR/$NOW
+        @sbindir@/rdup $R_OPT -N $STAMP $LIST $@ | \
+        @sbindir@/rdup-snap $OPT -b $BACKUPDIR/$NOW
         ;;
 esac
 chmod 755 $BACKUPDIR/$NOW               # hmmm
