some functions
git-svn-id: file:///svn/rdup/trunk@994 0f4cb41f-7f08-0410-98f9-8ec83d93c06f

diff --git a/sh-wrapper/rdup-snapshot.in b/sh-wrapper/rdup-snapshot.in
--- a/sh-wrapper/rdup-snapshot.in
+++ b/sh-wrapper/rdup-snapshot.in
@@ -113,7 +113,7 @@ if [[ ! $? ]]; then
 fi
 
 if [[ -z $ssh ]]; then
-        what $BCKUPDIR $NOW; purpose=$? # save return code from what
+        what $BACKUPDIR $NOW; purpose=$? # save return code from what
 else
         $ssh "source @datadir@/share/rdup/shared.sh; what $BACKUPDIR $NOW"
         $purpose=$?
@@ -131,5 +131,5 @@ esac
 # execute the backup command
 _echo2 "Executing: ${cmd}"
 eval ${cmd}
-chmod 755 $BACKUPDIR/$NOW               # hmmm
+chmod 755 $BACKUPDIR/$NOW
 exit 0
